# Generated by Django 5.1.6 on 2025-03-14 20:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_fyp', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_by_id', models.BigIntegerField()),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('internship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='posting', to='app_fyp.internship')),
            ],
            options={
                'db_table': 'internship_postings',
                'indexes': [models.Index(fields=['posted_at'], name='internship__posted__1a6df4_idx')],
            },
        ),
    ]
