# Generated by Django 5.1.6 on 2025-03-14 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship_posting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipposting',
            name='is_approved',
        ),
    ]
