# Generated by Django 5.1.6 on 2025-03-12 20:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('stack', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('stipend', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('internship_type', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('remote', 'Remote')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'internships',
                'indexes': [models.Index(fields=['title', 'company'], name='internships_title_2f3a5a_idx')],
            },
        ),
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('skills', models.TextField()),
                ('experience', models.TextField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='applications/resumes/')),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('projects', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='app_fyp.internship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'internship_applications',
                'indexes': [models.Index(fields=['user', 'status'], name='internship__user_id_37808b_idx')],
                'unique_together': {('user', 'internship')},
            },
        ),
    ]
